### ISSUE TITLE
Windows 7 provision error

### ISSUE THREAD

**Issue by kevinquillen** [alehkot/druphpet#14]
I am getting this error while provisioning on Windows, not sure what it means.

It built correctly the first time, then reload --provision throws this:

```
    default: Running: C:/Users/Kevin/AppData/Local/Temp/vagrant-shell20150225-220-o07w3d.sh
==> default: stdin: is not a tty
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: stdin: is not a tty
==> default: /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs'
==> default: :
==> default: Could not find 'puppet' (>= 0) among 21 total gem(s)
==> default:  (
==> default: Gem::LoadError
==> default: )
==> default: Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-2.2.0:/usr/local/rvm/gems/ruby-2.2.0@global', execute `gem e
v` for more information
==> default:    from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
==> default:    from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `g
m'
==> default:    from /usr/bin/puppet:22:in `<main>'
==> default:    from /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
==> default:    from /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by alehkot** [comment]
@kevinquillen Make sure you have the latest versions of Vagrant (1.7.2+) and VirtualBox (4.3.22) installed. Try to wipe the existing box completely:
In the folder of druphpet, execute:
`vagrant destroy`
`vagrant box remove "puphpet/ubuntu1404-x64"`
`vagrant up`

**Comment by kevinquillen** [comment]
Can't use Ruby version over 1.9.2 apparently.
